"use server";

import { revalidatePath } from "next/cache";

import { routes } from "@/config/routes";
import { grantAdminRepository } from "@/features/admin/repositories/grant-admin-repository";
import {
  grantClassificationSchema,
  grantCreateSchema,
  grantEditSchema,
  grantStatusSchema,
  toFundingFlags,
} from "@/features/admin/schemas/grant-edit-schema";
import { requireAdmin } from "@/features/admin/services/auth-service";
import type { ActionResult } from "@/lib/errors";
import { failure, success, toActionFailure } from "@/lib/errors";
import { logger } from "@/lib/logger";

/**
 * Every published change invalidates the public page as well as the admin one.
 * Forgetting the public path is how an operator publishes a grant, reloads the
 * site, and sees nothing.
 */
function revalidateGrant(slug: string): void {
  revalidatePath(routes.admin.grants);
  revalidatePath(routes.grants);
  revalidatePath(routes.grant(slug));
}

/**
 * Creates a grant by hand.
 *
 * The only route into the directory for a country with no crawler source,
 * which today is every country except the United States.
 *
 * The agency is resolved first, and may be created on the way: a country with
 * no agencies yet cannot offer one to pick, so refusing here would make the
 * form unusable for exactly the countries this exists to serve.
 */
export async function createGrant(
  input: unknown,
): Promise<ActionResult<{ grantId: string; slug: string }>> {
  const admin = await requireAdmin("editor");
  const parsed = grantCreateSchema.safeParse(input);

  if (!parsed.success) {
    return failure("VALIDATION_FAILED", parsed.error.issues[0]?.message ?? "Check the details.");
  }

  const values = parsed.data;

  try {
    const organizationId =
      values.organizationId ??
      (await grantAdminRepository.findOrCreateOrganization(
        (values.newOrganizationName ?? "").trim(),
        values.countryId,
        values.newOrganizationWebsite ?? null,
      ));

    const flags = toFundingFlags(values.fundingLevel);

    // A category that is not among the selected ones cannot be the primary.
    // The form prevents it; a hand-built request would not.
    const primaryCategoryId =
      values.primaryCategoryId !== null &&
      values.primaryCategoryId !== undefined &&
      values.categoryIds.includes(values.primaryCategoryId)
        ? values.primaryCategoryId
        : (values.categoryIds[0] ?? null);

    const grantId = await grantAdminRepository.create(
      {
        title: values.title,
        country_id: values.countryId,
        organization_id: organizationId,
        state_id: values.stateId ?? null,
        short_description: values.shortDescription,
        full_description: values.fullDescription,
        eligibility: values.eligibility,
        minimum_amount: values.minimumAmount,
        maximum_amount: values.maximumAmount,
        official_url: values.officialUrl,
        application_url: values.applicationUrl,
        // Where a hand-entered grant came from is the official notice itself.
        source_url: values.officialUrl,
        opens_at: values.opensAt,
        closes_at: values.closesAt,
        status: values.status,
        is_federal: flags.isFederal,
        is_private: flags.isPrivate,
      },
      values.categoryIds,
      primaryCategoryId,
      values.changeReason ?? "created in admin panel",
    );

    const created = await grantAdminRepository.findById(grantId);

    logger.info("Grant created", {
      feature: "admin",
      action: "createGrant",
      userId: admin.id,
      grantId,
    });

    // The slug is generated by the database, so the public path is only known
    // after the insert. Revalidating the wrong path is how an operator saves a
    // grant and then cannot find it.
    if (created !== null) {
      revalidateGrant(created.slug);
    } else {
      revalidatePath(routes.admin.grants);
      revalidatePath(routes.grants);
    }

    return success({ grantId, slug: created?.slug ?? "" });
  } catch (error) {
    return toActionFailure(error, { feature: "admin", action: "createGrant" });
  }
}

/**
 * Changes what a grant is filed under — country, agency, state, categories and
 * funding level. Separate from `saveGrant`, which only touches text.
 */
export async function saveGrantClassification(
  input: unknown,
): Promise<ActionResult<{ grantId: string }>> {
  const admin = await requireAdmin("editor");
  const parsed = grantClassificationSchema.safeParse(input);

  if (!parsed.success) {
    return failure("VALIDATION_FAILED", parsed.error.issues[0]?.message ?? "Check the details.");
  }

  const values = parsed.data;

  try {
    const existing = await grantAdminRepository.findById(values.grantId);

    if (existing === null) {
      return failure("NOT_FOUND", "That grant no longer exists.");
    }

    if (existing.status === "published" && values.categoryIds.length === 0) {
      return failure(
        "VALIDATION_FAILED",
        "A published grant needs at least one category. Unpublish it first, or keep one.",
      );
    }

    const flags = toFundingFlags(values.fundingLevel);
    const primaryCategoryId =
      values.primaryCategoryId !== null &&
      values.primaryCategoryId !== undefined &&
      values.categoryIds.includes(values.primaryCategoryId)
        ? values.primaryCategoryId
        : (values.categoryIds[0] ?? null);

    await grantAdminRepository.setClassification(
      {
        grantId: values.grantId,
        countryId: values.countryId,
        organizationId: values.organizationId,
        stateId: values.stateId ?? null,
        categoryIds: values.categoryIds,
        primaryCategoryId,
        isFederal: flags.isFederal,
        isPrivate: flags.isPrivate,
      },
      values.changeReason ?? "classification changed in admin panel",
    );

    logger.info("Grant classification changed", {
      feature: "admin",
      action: "saveGrantClassification",
      userId: admin.id,
      grantId: values.grantId,
    });

    revalidateGrant(existing.slug);

    return success({ grantId: values.grantId });
  } catch (error) {
    return toActionFailure(error, { feature: "admin", action: "saveGrantClassification" });
  }
}

export async function saveGrant(input: unknown): Promise<ActionResult<{ grantId: string }>> {
  const admin = await requireAdmin("editor");
  const parsed = grantEditSchema.safeParse(input);

  if (!parsed.success) {
    return failure("VALIDATION_FAILED", parsed.error.issues[0]?.message ?? "Check the details.");
  }

  const { grantId, changeReason, ...values } = parsed.data;

  try {
    const existing = await grantAdminRepository.findById(grantId);

    if (existing === null) {
      return failure("NOT_FOUND", "That grant no longer exists.");
    }

    await grantAdminRepository.save(
      grantId,
      {
        title: values.title,
        short_description: values.shortDescription,
        full_description: values.fullDescription,
        eligibility: values.eligibility,
        minimum_amount: values.minimumAmount,
        maximum_amount: values.maximumAmount,
        official_url: values.officialUrl,
        application_url: values.applicationUrl,
        opens_at: values.opensAt,
        closes_at: values.closesAt,
        ...(values.featured === undefined ? {} : { featured: values.featured }),
      },
      changeReason ?? "edited in admin panel",
    );

    logger.info("Grant edited", {
      feature: "admin",
      action: "saveGrant",
      userId: admin.id,
      grantId,
    });

    revalidateGrant(existing.slug);

    return success({ grantId });
  } catch (error) {
    return toActionFailure(error, { feature: "admin", action: "saveGrant" });
  }
}

export async function setGrantStatus(
  input: unknown,
): Promise<ActionResult<{ grantId: string; status: string }>> {
  const admin = await requireAdmin("editor");
  const parsed = grantStatusSchema.safeParse(input);

  if (!parsed.success) {
    return failure("VALIDATION_FAILED", parsed.error.issues[0]?.message ?? "Check the details.");
  }

  try {
    const existing = await grantAdminRepository.findById(parsed.data.grantId);

    if (existing === null) {
      return failure("NOT_FOUND", "That grant no longer exists.");
    }

    if (parsed.data.status === "published" && existing.categoryNames.length === 0) {
      // The database refuses this too. Catching it here turns a constraint
      // violation into a sentence explaining what to do about it.
      return failure(
        "VALIDATION_FAILED",
        "This grant has no category, so it cannot be published. Assign one first.",
      );
    }

    await grantAdminRepository.setStatus(
      parsed.data.grantId,
      parsed.data.status,
      parsed.data.reason ?? `status changed to ${parsed.data.status}`,
    );

    logger.info("Grant status changed", {
      feature: "admin",
      action: "setGrantStatus",
      userId: admin.id,
      grantId: parsed.data.grantId,
      status: parsed.data.status,
    });

    revalidateGrant(existing.slug);

    return success({ grantId: parsed.data.grantId, status: parsed.data.status });
  } catch (error) {
    return toActionFailure(error, { feature: "admin", action: "setGrantStatus" });
  }
}

export async function deleteGrant(input: unknown): Promise<ActionResult<{ grantId: string }>> {
  // Admin, not editor: this removes a grant from the directory.
  const admin = await requireAdmin("admin");
  const parsed = grantStatusSchema.pick({ grantId: true, reason: true }).safeParse(input);

  if (!parsed.success) {
    return failure("VALIDATION_FAILED", "Could not identify that grant.");
  }

  try {
    const existing = await grantAdminRepository.findById(parsed.data.grantId);

    if (existing === null) {
      return failure("NOT_FOUND", "That grant no longer exists.");
    }

    await grantAdminRepository.softDelete(
      parsed.data.grantId,
      parsed.data.reason ?? "deleted in admin panel",
    );

    logger.info("Grant deleted", {
      feature: "admin",
      action: "deleteGrant",
      userId: admin.id,
      grantId: parsed.data.grantId,
    });

    revalidateGrant(existing.slug);

    return success({ grantId: parsed.data.grantId });
  } catch (error) {
    return toActionFailure(error, { feature: "admin", action: "deleteGrant" });
  }
}
